version: '2'
services:
  web:
    image: "k0zakinio/arrange-anything"
    ports:
     - "8080:8080"
  postgres:
    image: "postgres"
    volumes:
          - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb