version: '2'
services:
  web:
    image: "k0zakinio/arrange-anything"
    ports:
     - "8080:8080"
  postgres:
    image: "postgres:9.6"
    volumes:
          - /var/lib/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb