version: '2'
services:
  web:
    image: "k0zakinio/arrange-anything"
    ports:
     - "8080:8080"
    links:
     - "postgres:postgres.local"
  postgres:
    image: "postgres:9.6"
    ports:
     - "5432:5432"
    volumes:
          - /var/lib/aa_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb